Improve resilience of rabbitmq dispatcher and mongodb initialization
JGCarmona-Consulting/tfst pull request #51
Opened 2024-11-24 20:24 UTC by jaardila-3

web reference health checks: https://medium.com/@jeslurrahman/implementing-health-checks-in-net-8-c3ba10af83c3

2024-12-02 12:03 UTC, juangcarmona requested changes
In general looks good but we have inherited (my mistake) some code that looks core, and we might pay special attention to it.

2024-12-02 12:03 UTC, juangcarmona commented on src/api/TheFullStackTeam.API/Program.cs
> +        builder.Services.AddCustomHealthChecks(builder.Configuration);
After adding custom health checks, we should map separate endpoints for liveness and readiness checks in the middleware. This helps differentiate application availability from the readiness to handle incoming requests, which is especially useful in orchestration tools like Kubernetes.

2024-12-02 12:03 UTC, juangcarmona commented on src/api/TheFullStackTeam.API/Program.cs
> +        app.MapHealthChecks("/api/health", new HealthCheckOptions()
Consider replacing /api/health with two different endpoints: /health/liveness for basic application health and /health/readiness for critical dependency checks. Use Predicate to filter checks by their tags (liveness or readiness). This approach will improve the application lifecycle management, particularly in cloud deployments.

i.e.:

```
app.MapHealthChecks("/health/liveness", new HealthCheckOptions
{
    Predicate = (check) => check.Tags.Contains("liveness"),
    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
});

app.MapHealthChecks("/health/readiness", new HealthCheckOptions
{
    Predicate = (check) => check.Tags.Contains("readiness"),
    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
});
```
The idea is to Split the /api/health endpoint into two endpoints: /health/liveness for verifying that the app process is running, and /health/readiness for checking the status of dependencies like databases and message brokers. This helps Kubernetes and other orchestrators make better decisions about container restarts or taking the instance out of the load balancer.

2024-12-03 15:37 UTC, jaardila-3 commented on src/api/TheFullStackTeam.Infrastructure/Messaging/RabbitMq/RabbitMQEventDispatcher.cs
> +        _connection = new Lazy<IConnection>(() =>
resolved

2024-12-08 17:10 UTC, jaardila-3 commented on src/api/TheFullStackTeam.API/Program.cs
> +        builder.Services.AddCustomHealthChecks(builder.Configuration);
I didn't understand the difference between the previous suggestion and this one.

2024-12-08 20:21 UTC, jaardila-3 commented on src/api/TheFullStackTeam.API/Program.cs
> +namespace TheFullStackTeam.Api;
I Added .editorconfig to Solution and I Used File-Scoped Namespace

2024-12-09 15:27 UTC, juangcarmona approved these changes
The only Change I need is to translate those comments into spanish

2024-12-09 15:31 UTC, merged